### ISSUE TITLE
hreflang in when product visibility is different at store view level

### ISSUE THREAD

**Issue by paugnu** [Web200/magento-seo#1]
Hi,

I've run into an issue which might be specific of my own store, but I'll raise it anyway:

- We have products that are visible in store view 'Spanish'
- But the same product might not be visible in French or English

This means that the hreflang link won't be correct because the product is not visible in the store. I think it should be necessary to add a particular condition for this. In the CategoryUrlProvider and ProductUrlProvider it's easy to add the condition.

**Comment by kpitn** [comment]
Hi @paugnu 

Sorry for the late fix.

it's fix in the last version v0.5.4

**Comment by paugnu** [comment]
Merci, Pierre :)
